# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

iterate_ant <- function(X, iters, row, col, c) {
    .Call('_aRtsy_iterate_ant', PACKAGE = 'aRtsy', X, iters, row, col, c)
}

iterate_circlemap <- function(X, kmin, kmax, phimin, phimax, iterations) {
    .Call('_aRtsy_iterate_circlemap', PACKAGE = 'aRtsy', X, kmin, kmax, phimin, phimax, iterations)
}

iterate_mondriaan <- function(X, neighbors, s, cuts, ratio) {
    .Call('_aRtsy_iterate_mondriaan', PACKAGE = 'aRtsy', X, neighbors, s, cuts, ratio)
}

iterate_planet <- function(X, radius, xcenter, ycenter, threshold, iterations, starprob, ncolors, colorsused, fade, lightright) {
    .Call('_aRtsy_iterate_planet', PACKAGE = 'aRtsy', X, radius, xcenter, ycenter, threshold, iterations, starprob, ncolors, colorsused, fade, lightright)
}

iterate_strokes <- function(X, neighbors, s, p) {
    .Call('_aRtsy_iterate_strokes', PACKAGE = 'aRtsy', X, neighbors, s, p)
}

iterate_turmite <- function(X, iters, row, col, p) {
    .Call('_aRtsy_iterate_turmite', PACKAGE = 'aRtsy', X, iters, row, col, p)
}

