# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

iterate_ant <- function(X, iters, row, col, c, seed) {
    .Call('_aRtsy_iterate_ant', PACKAGE = 'aRtsy', X, iters, row, col, c, seed)
}

iterate_strokes <- function(X, neighbors, s, p, seed) {
    .Call('_aRtsy_iterate_strokes', PACKAGE = 'aRtsy', X, neighbors, s, p, seed)
}

iterate_turmite <- function(X, iters, row, col, p, seed) {
    .Call('_aRtsy_iterate_turmite', PACKAGE = 'aRtsy', X, iters, row, col, p, seed)
}

